### ISSUE TITLE
Issues with LMMs-EVAL for LLaVA-1.5-7B on ScienceQA and SeedBench

### ISSUE THREAD

**Issue by Breeze-zyuhan** [EvolvingLMMs-Lab/lmms-eval#236]
Hi,

Thank you for your excellent work! I've encountered two issues while using LMMs-EVAL to assess LLaVA-1.5-7B on ScienceQA (Image) and SeedBench:

<img width="677" alt="WechatIMG465" src="https://github.com/user-attachments/assets/f4289880-ba40-4b5b-86f8-5cdced247b66">
<img width="674" alt="WechatIMG464" src="https://github.com/user-attachments/assets/3f47d52e-795e-49a8-9e46-a524e7dcac2b">

1. **ScienceQA:** I noticed that changing the batch_size from 1 to 2 led to a performance drop from 69.56 to 58.70. Is such a significant variation expected?
2. **SeedBench:** For batch sizes of 1 and 2, LMMs-EVAL reported performances of 53.58 and 50.99, respectively. These results do not align with the official number of 60.49 listed in your [spreadsheet](https://docs.google.com/spreadsheets/d/1a5ImfdKATDI8T7Cwh6eH-bEsnQFzanFraFUgcS9KHWc/edit?gid=0#gid=0).

I'm running these evaluations in a different setup (torch 2.1.2 + cuda-11.2). Could this be affecting the outcomes, or might there be another issue?

Thank you for looking into this.

**Comment by kcz358** [comment]
We do not recommend you to run llava with batch_size larger than 1 because it has some problem with batch inferencing and batch inferencing may be inaccurate in this case. If you are seeking batch inference, you may check srt model or llava sglang that use sglang as a server to perform inferencing.

For seedbench, the results are not aligned because we slightly changes the logic of the image tokens. Previously we only append one image token for llava in seedbench even when evaluating videos but now we append one image token for each frames and causing the score of video to decrease.
