### ISSUE TITLE
quetions about the evals

### ISSUE THREAD

**Issue by CrossLee1** [EvolvingLMMs-Lab/lmms-eval#6]
Thanks for your great work!

I have some questions about the evaluation results.
1. TextVQA, results of  llava-1.5-13B get score of 61.3 in the paper, but in the sheet https://docs.google.com/spreadsheets/d/1a5ImfdKATDI8T7Cwh6eH-bEsnQFzanFraFUgcS9KHWc/edit#gid=0, the result is only 48.73, why?
2. After executing the command as README, the generated submission file of mmbench seems wrong. When I upload it to the evaluation server, I got the logs "Your excel file should have a column named `A`, please double check and submit again"

hope to get your response, thanks ~

**Comment by Luodian** [comment]
I think it's because llava reports the `test` result meanwhile we are reporting `val` split.

Running textvqa will get both val metric result and a submission file for test split.

And users may submit the file to https://eval.ai/web/challenges/challenge-page/874/ to get the results.

Maybe @pufanyi could address this more clearly.

**Comment by CrossLee1** [comment]
@Luodian @pufanyi thanks for your reply, as for the question 2, do you have any ideas?

**Comment by Luodian** [comment]
As for MMBench, We are updating it in a new PR.
